#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 33447-lb-01
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 33447-web-01 18.232.49.228 check
        server 33447-web-02 54.209.217.6 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
