#!/bin/bash
mv /tmp/my_first_directory
#!/bin/bash
mv /tmp/betty /tmp/my_first_directory
rm 0x00-shell_basics/7-movethatfile/#!/bin/bash
rm 0x00-shell_basics/7-movethatfile/mv /tmp/my_first_directory
